layout_spectrum: 0.232715
color:
  saturation: 0.6357504
  brandStrength: 0.4637437
  lightness: 0.688027
  brandColors:
    - '#534B30'
    - '#E0B56E'
    - '#706C4C'
    - '#F2D1AA'
    - '#884316'
  rhythmicContrast: 0.6838111
typography_spectrum: 0.5236087
name: Shit Everywhere
