color:
  brandColors:
    - '#B0B8D0'
    - '#782820'
    - '#6878A0'
    - '#A03020'
    - '#B0D8F8'
  brandStrength: 0.463743
  lightness: 0.688027
  rhythmicContrast: 0.683811
  saturation: 0.63575
layout_spectrum: 0.232715
name: Shit Everywhere
typography_spectrum: 0.523608
